//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TuniacGoonVisualPlugin.rc
//
#define IDD_TUNIACGOOMPREFWINDOW        101
#define IDC_TUNIACGOOMPREF_USEPBO       1001
#define IDC_TUNIACGOOMPREF_USEMAPPEDPBO 1003
#define IDC_TUNIACGOOMPREF_ALLOWNONPOWEROF2 1004
#define IDC_TUNIACGOOMPREF_MAXVISRES    1006
#define IDC_TUNIACGOOMPREF_MAXRESOLUTIONTEXT 1007
#define IDC_TUNIACGOOMPREF_ACCELBOX     1008
#define IDC_TUNIACGOOMPREF_VISRENDER    1009
#define IDC_TUNIACGOOMPREF_USEOPENGL    1010
#define IDC_TUNIACGOOMPREF_USEGDI       1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
