//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tuniac.rc
//
#define IDR_TUNIAC_MENU                 101
#define IDD_ALBUMARTISTVIEW             102
#define IDD_SOURCESELECTOR              103
#define IDD_ADDOTHER                    104
#define IDD_ADDINGFILES                 105
#define IDD_PLAYLISTSOURCE              106
#define IDD_PREFERENCES_AUDIO           107
#define IDI_TUNIAC                      108
#define IDI_THEMEICON_PLAYLIST_MEDIALIBRARY 109
#define IDC_ADDARROW                    110
#define IDD_ALBUMFILTER                 111
#define IDC_NEWPLAYLISTARROW            112
#define IDI_THEMEICON_PLAYLIST_STANDARD 113
#define IDD_EDITOR_SONG                 114
#define IDD_EDITOR_FILE                 115
#define IDD_EDITOR_MISC                 116
#define IDD_PLAYLISTVIEW_VIEWOPTIONS    117
#define IDD_PREFERENCES_MEDIALIBRARY    118
#define IDR_MAINWINDOWACCEL             119
#define IDD_PREFERENCES_COREAUDIO       120
#define IDD_CDAUDIOSOURCE               121
#define IDI_THEMEICON_PLAYLIST_CD       122
#define IDD_PREFERENCES_IMPORTING       123
#define IDD_BUFFERING                   124
#define IDR_VISMENU                     125
#define IDD_PREFERENCES_VISUALS         126
#define IDD_SAVINGLIBRARY               127
#define IDD_PREFERENCES_GENERAL         128
#define IDD_PREFERENCES_FILEASSOC       129
#define IDD_PREFERENCES_EQ              130
#define IDR_TRAYMENU                    131
#define IDD_PREFERENCES_PLUGINS         132
#define IDR_PLAYLISTITEM_MENU           133
#define IDR_SOURCESELECT_MENU           134
#define IDR_FILTERBYFIELD_MENU          135
#define IDR_SOURCESELECT_DRAGMENU       136
#define IDI_THEMEICON_ITEM_NORMAL       137
#define IDI_THEMEICON_ITEM_ACTIVE       138
#define IDD_PREFERENCES                 139
#define IDD_PREFERENCES_FORMATTING      140
#define IDR_PLAYLISTHEADER_MENU         141
#define IDD_LOGVIEW                     142
#define IDB_EDITINFO                    143
#define IDB_NEXT                        180
#define IDB_PAUSE                       181
#define IDB_PLAY                        182
#define IDB_PREVIOUS                    183
#define IDB_REPEATALL                   184
#define IDB_REPEATNONE                  185
#define IDB_REPEATONE                   186
#define IDB_SHUFFLEOFF                  187
#define IDB_SHUFFLEON                   188
#define IDD_ABOUTBOX                    189
#define IDI_THEMEICON_ITEM_UNAVAILABLE  190
#define IDC_ADDOTHER_ADD                1001
#define IDC_ADDOTHER_EDIT               1002
#define IDC_ADDOTHER_CANCEL             1003
#define IDC_ADDINGFILES_PROGRESS        1004
#define IDC_BUFFERING_PROGRESS          1005
#define IDC_SOURCESELECTOR              1006
#define IDC_PLAYLIST_FILTER             1008
#define IDC_PLAYLIST_LIST               1009
#define IDC_CROSSFADE_ENABLE            1010
#define IDC_BUFFER_TIME_SLIDER          1011
#define IDC_CROSSFADE_TIME_SLIDER       1012
#define IDD_FILTERSELECTOR              1040
#define IDC_FILTER_ARTIST               1041
#define IDC_CROSSFADE_TIME_TEXT         1042
#define IDC_MEDIALIBRARY_TEXT           1043
#define IDC_TITLE_EDIT                  1044
#define IDC_BUFFER_TIME_TEXT            1045
#define IDC_ARTIST_COMBO                1046
#define IDC_RATING_CONTROL              1047
#define IDC_TRACKNO_EDIT                1048
#define IDC_PLAYTIME_TEXT               1049
#define IDC_TRACKMAX_EDIT               1050
#define IDC_SAMPLERATE_TEXT             1051
#define IDC_ALBUM_COMBO                 1052
#define IDC_CHANNELS_TEXT               1053
#define IDC_YEAR_EDIT                   1054
#define IDC_BITRATE_TEXT                1055
#define IDC_GENRE_COMBO                 1056
#define IDC_PLAYLISTVIEWOPTIONS_LIST    1057
#define IDC_REBUILD_ML                  1058
#define IDC_CONSOLIDATE_BUTTON          1059
#define IDC_MEDIALIBRARYBROWSE_BUTTON   1060
#define IDC_PLAYLIST_SOURCE_MAKEPLAYLIST 1061
#define IDC_PLAYLIST_SOURCE_CLEARFILTER 1062
#define IDC_ALBUMARTIST_ALBUMLIST       1063
#define IDC_ALBUMARTIST_ARTISTLIST      1064
#define IDC_ALBUMARTIST_PLAYLISTLIST    1065
#define IDC_CDSOURCE_TRACKLIST          1066
#define IDC_AUDIOPLUGIN_CONFIGURE       1067
#define IDC_AUDIOPLUGIN_ABOUT           1068
#define IDC_GENRECHK                    1069
#define IDC_RATINGCHK                   1070
#define IDC_ALBUMNAMECHK                1071
#define IDC_TRACKNUMCHK                 1072
#define IDC_TRACKYEARCHK                1073
#define IDC_TRKTITLECHK                 1074
#define IDC_ARTISTCHK                   1075
#define IDC_BUFFERING_INFO              1076
#define IDC_VISUAL_FPS                  1077
#define IDC_AUDIOPLUGINS_LIST           1078
#define IDC_SAVINGLIBRARY_PROGRESS      1079
#define IDC_SOURCE_ADDPLAYLIST          1080
#define IDC_SOURCE_DELPLAYLIST          1081
#define IDC_CDTITLE                     1082
#define IDC_GENERAL_TASKBAR_NORMAL      1083
#define IDC_GENERAL_TASKBAR_MINIMIZE    1084
#define IDC_GENERAL_PAUSEONLOCK         1085
#define IDC_GENERAL_FOLLOWCURRENTSONG   1086
#define IDC_FORMATTING_WINDOWTITLEFORMAT 1087
#define IDC_FORMATTING_PLUGINFORMAT     1088
#define IDC_FORMATTING_LISTFORMAT       1089
#define IDC_FORMATTING_FORMATSTRING_HELP 1090
#define IDC_ADDINGFILES_COUNT           1111
#define IDC_GENERAL_PAUSEONSCREENSAVE   1112
#define IDC_GENERAL_HISTORYCOUNT_SPINNER 1114
#define IDC_GENERAL_HISTORYCOUNT        1115
#define IDC_GENERAL_FUTURECOUNT_SPINNER 1116
#define IDC_GENERAL_FUTURECOUNT         1117
#define IDC_PLAYLIST_SOURCE_SELECTFILTERBYFIELD 1118
#define IDC_GENERAL_SMARTSORTING        1119
#define IDC_BUFFERING_CANCEL            1121
#define IDC_PLUGINS_LIST                1123
#define IDC_PLUGINS_ABOUT               1124
#define IDC_PLUGINS_CONFIGURE           1125
#define IDC_PLUGINS_DISABLEALL          1126
#define IDC_PLUGINS_ENABLEALL           1127
#define IDC_PREFERENCES_TREE            1128
#define IDC_OK                          1129
#define IDC_PLAYLISTSOURCE_FILTERCOMBO  1136
#define IDC_GENERAL_MINIMIZEONCLOSE     1137
#define IDC_VISUAL_CHANGERESCOMBO       1138
#define IDC_DEVICESELECTOR_COMBO        1138
#define IDC_VISUAL_FPSDISPLAY           1141
#define IDC_VISUAL_CHANGERESCHECK       1142
#define IDC_CDSOURCE_IMPORT             1143
#define IDC_LOGVIEW_EDIT                1144
#define IDC_LOGVIEW_CLEAR               1145
#define IDC_LOGVIEW_ENABLE              1146
#define IDC_AUDIO_REPLAYGAIN            1148
#define IDC_AUDIO_REPLAYGAINALBUM       1149
#define IDC_GENERAL_ARTONSELECTION      1149
#define IDC_AUDIO_AMPGAINSLIDER         1150
#define IDC_GENERAL_SHOWVISART          1150
#define IDC_ABOUT_BUILD_TEXT            1151
#define IDC_GENERAL_SHOWALBUMART        1151
#define IDC_GENERAL_ALBUMARTBOX         1152
#define IDC_FILETIMETODATEADDED         1153
#define IDC_LIBRARY_FILETIMETODATEADDED 1153
#define IDC_AUDIO_AMPGAINTEXT           1154
#define IDC_LIBRARY_PLAYLISTSORTING     1155
#define IDC_LIBRARY_AUTOADDPLAYLIST     1156
#define IDC_FILEASSOC_TYPEDEFAULT_UPDATE 1160
#define IDC_FILEASSOC_TYPEDEFAULT       1161
#define IDC_FILEASSOC_TYPE_OPEN         1162
#define IDC_FILEASSOC_TYPE_PLAY         1163
#define IDC_FILEASSOC_TYPE_QUEUE        1164
#define IDC_FILEASSOC_SETDEFAULT        1165
#define IDC_FILEASSOC_ADDTHESE          1166
#define IDC_FILEASSOC_ACTIONTEXT        1167
#define IDC_FILEASSOC_WARNINGTEXT       1168
#define IDC_FILEASSOC_REGASSOC          1169
#define IDC_EQLOW_SLIDER                1180
#define IDC_EQMID_SLIDER                1181
#define IDC_EQHIGH_SLIDER               1182
#define IDC_EQLOW_TEXT                  1183
#define IDC_EQMID_TEXT                  1184
#define IDC_EQHIGH_TEXT                 1185
#define IDC_EQ_GROUP                    1186
#define IDC_EQRESET_BUTTON              1187
#define IDC_EQ_ENABLE                   1188
#define IDC_CHECK1                      1190
#define IDC_GENERAL_AUTOSOFTPAUSE       1190
#define IDC_LIBRARY_ADDSINGLESTREAM     1190
#define IDC_ABOUTBOXTHANKS_TEXT         1191
#define IDC_ABOUTBOXDEV_TEXT            1192
#define IDC_ABOUTBOXTUNIAC_TEXT         1193
#define IDC_GENERAL_SCREEN_ALLOW        1194
#define IDC_GENERAL_SCREEN_PREVENT      1195
#define IDC_RADIO1                      1196
#define IDC_GENERAL_SCREEN_PREVENTFULL  1196
#define ID_FILE_EXIT                    40001
#define ID_FILE_NEWPLAYLIST_NORMALPLAYLIST 40002
#define ID_FILE_NEWPLAYLIST_SMARTPLAYLIST 40003
#define ID_FILE_ADDFILES                40004
#define ID_FILE_ADDDIRECTORY            40005
#define ID_FILE_ADDOTHER                40006
#define ID_EDIT_PREFERENCES             40007
#define ID_HELP_ABOUT                   40009
#define ID_EDIT_EDITFILEINFORMATION     40012
#define ID_HELP_TUNIACHELP              40013
#define ID_HELP_HOMEPAGE                40014
#define ID_PLAYBACK_NEXT                40015
#define ID_PLAYBACK_PREVIOUS            40016
#define ID_PLAYBACK_PLAYPAUSE           40017
#define ID_FILE_OPENSTREAM              40018
#define ID_PLAYBACK_REPEATMODE          40019
#define ID_EDIT_SHOWCOLUMNSELECTION     40021
#define ID_REPEAT_OFF                   40028
#define ID_REPEAT_ONETRACK              40030
#define ID_REPEAT_ALLTRACKS             40031
#define ID_VIS_CONFIGURE                40038
#define ID_VIS_ABOUT                    40039
#define ID_FILE_FORCESAVEMEDIALIBRARY   40040
#define ID_PLAYBACK_SHOWCURRENTLYPLAYINGTRACK 40041
#define ID_VIS_FULLSCREEN               40045
#define ID_APP_SHOW                     40048
#define ID_PLAYBACK_SEEKFORWARD         40050
#define ID_PLAYBACK_SEEKBACK            40051
#define ID_PLAYBACK_STOP                40052
#define ID_PLAYBACK_PAUSE               40053
#define ID_PLAYBACK_PLAY                40054
#define ID_PLAYBACK_TOGGLE_SHUFFLE      40055
#define ID_PLAYBACK_TOGGLE_REPEAT       40056
#define ID_PLAY                         40059
#define ID_REMOVE                       40062
#define ID_UPDATE                       40063
#define ID_TONEWPLAYLIST                40066
#define ID_FILTERBYFIELD                40067
#define ID_PLAYPLAYLIST                 40069
#define ID_PAUSEHERE                    40071
#define ID_PLAYBACK_SOFTPAUSE           40072
#define ID_EDIT_ALWAYSONTOP             40073
#define ID_SAVEORDER                    40074
#define ID_RESTOREORDER                 40075
#define ID_PLAYNEXT                     40080
#define ID_QUEUE                        40081
#define ID_PLAYBACK_CLEARQUEUE          40082
#define ID_PLAYBACK_PREVIOUS_BYHISTORY  40090
#define ID_REPEAT_ALLQUEUED             40093
#define ID_FILTERBY_ARTIST              40105
#define ID_FILTERBY_NORMAL              40106
#define ID_FILTERBY_TITLE               40107
#define ID_FILTERBY_ALBUM               40108
#define ID_FILTERBY_GENRE               40109
#define ID_FILTERBY_YEAR                40110
#define ID_FILTERBY_COMMENT             40111
#define ID_FILTERBY_URL                 40112
#define ID_FILTERBY_FILENAME            40113
#define ID_FILTERBY_EXTENSION           40114
#define ID_PLAYBACK_RANDOMNEXT          40115
#define ID_PLAYLISTS                    40118
#define ID_PLAYLISTS_MEDIALIBRARY       40119
#define ID_PLAYBACK_CLEARPAUSEAT        40121
#define ID_RENAME                       40122
#define ID_COPYTO                       40126
#define ID_MERGEINTO                    40127
#define ID_REMOVEFROM                   40128
#define ID_QUEUEBYFIELD                 40130
#define ID_FILE_EXPORTPLAYLIST          40131
#define ID_EXPORT                       40134
#define ID_REMOVEDUPLICATES             40135
#define ID_FILTERBY                     40141
#define ID_SHOWFILE                     40148

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         40149
#define _APS_NEXT_CONTROL_VALUE         1197
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
