//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tuniac.rc
//
#define IDR_TUNIAC_MENU                 101
#define IDR_TRAYMENU                    102
#define IDR_PLAYLISTITEM_MENU           103
#define IDR_SOURCESELECT_MENU           104
#define IDR_FILTERBYFIELD_MENU          105
#define IDR_SOURCESELECT_DRAGMENU       106
#define IDR_PLAYLISTHEADER_MENU         107
#define IDR_VISMENU                     108

#define IDI_TUNIAC                      150
#define IDI_THEMEICON_ITEM_NORMAL       151
#define IDI_THEMEICON_ITEM_ACTIVE       152
#define IDI_THEMEICON_PLAYLIST_STANDARD 153
#define IDI_THEMEICON_PLAYLIST_CD       154
#define IDI_THEMEICON_ITEM_UNAVAILABLE  155
#define IDI_THEMEICON_PLAYLIST_MEDIALIBRARY_ACTIVE 156
#define IDI_THEMEICON_PLAYLIST_STANDARD_ACTIVE 157
#define IDI_THEMEICON_PLAYLIST_CD_ACTIVE 158
#define IDI_THEMEICON_PLAYLIST_MEDIALIBRARY 159
#define IDD_PREFERENCES_SERVICES        195
#define IDB_NEXT                        201
#define IDB_PAUSE                       202
#define IDB_PLAY                        203
#define IDB_PREVIOUS                    204
#define IDB_REPEATALL                   205
#define IDB_REPEATNONE                  206
#define IDB_REPEATONE                   207
#define IDB_SHUFFLEOFF                  208
#define IDB_SHUFFLEON                   209
#define IDB_EDITINFO                    210

#define IDD_ADDOTHER                    251
#define IDD_ADDINGFILES                 252
#define IDD_BUFFERING                   253
#define IDD_SAVINGLIBRARY               254

#define IDD_SOURCESELECTOR              255
#define IDD_PLAYLISTSOURCE              256
#define IDD_CDAUDIOSOURCE               257
#define IDD_LOGVIEW                     258
#define IDD_ABOUTBOX                    259
#define IDD_TUNIACVISPREFWINDOW         260

#define IDD_ALBUMFILTER                 261

#define IDD_EDITOR_SONG                 262
#define IDD_EDITOR_FILE                 263
#define IDD_EDITOR_MISC                 264
#define IDD_PLAYLISTVIEW_VIEWOPTIONS    265
#define IDD_FILTERSELECTOR              266

#define IDR_MAINWINDOWACCEL             267

#define IDD_PREFERENCES                 268
#define IDD_PREFERENCES_AUDIO           269
#define IDD_PREFERENCES_VISUALS         270
#define IDD_PREFERENCES_GENERAL         271
#define IDD_PREFERENCES_FILEASSOC       272
#define IDD_PREFERENCES_EQ              273
#define IDD_PREFERENCES_PLUGINS         274
#define IDD_PREFERENCES_COREAUDIO       275
#define IDD_PREFERENCES_MEDIALIBRARY    276
#define IDD_PREFERENCES_FORMATTING      277
#define IDD_PREFERENCES_USERSEARCHFIELD 278
#define IDD_PREFERENCES_INTERFACE       279
#define IDC_NEWPLAYLISTARROW            280
#define IDC_ADDARROW                    281
#define IDC_ADDINGFILES_COUNT           1001
#define IDC_ADDOTHER_ADD                1002
#define IDC_ADDOTHER_EDIT               1003
#define IDC_ADDOTHER_CANCEL             1004
#define IDC_ABOUTBOXTHANKS_TEXT         1005
#define IDC_ABOUTBOXDEV_TEXT            1006
#define IDC_ABOUTBOXTUNIAC_TEXT         1007
#define IDC_ABOUT_BUILD_TEXT            1008
#define IDC_ADDINGFILES_PROGRESS        1009
#define IDC_BUFFERING_PROGRESS          1010
#define IDC_SAVINGLIBRARY_PROGRESS      1011
#define IDC_SOURCESELECTOR              1012
#define IDC_BUFFER_TIME_SLIDER          1013
#define IDC_BUFFER_TIME_TEXT            1014
#define IDC_CROSSFADE_TIME_SLIDER       1015
#define IDC_CROSSFADE_ENABLE            1016
#define IDC_CROSSFADE_TIME_TEXT         1017
#define IDC_FILTER_ARTIST               1018
#define IDC_TITLE_EDIT                  1019
#define IDC_ARTIST_COMBO                1020
#define IDC_RATING_CONTROL              1021
#define IDC_TRACKNO_EDIT                1022
#define IDC_PLAYTIME_TEXT               1023
#define IDC_TRACKMAX_EDIT               1024
#define IDC_SAMPLERATE_TEXT             1025
#define IDC_ALBUM_COMBO                 1026
#define IDC_CHANNELS_TEXT               1027
#define IDC_YEAR_EDIT                   1028
#define IDC_BITRATE_TEXT                1029
#define IDC_GENRE_COMBO                 1030
#define IDC_PLAYLISTVIEWOPTIONS_LIST    1031
#define IDC_REBUILD_ML                  1032
#define IDC_CONSOLIDATE_BUTTON          1033
#define IDC_MEDIALIBRARY_TEXT           1034
#define IDC_MEDIALIBRARYBROWSE_BUTTON   1035
#define IDC_PLAYLIST_SOURCE_MAKEPLAYLIST 1036
#define IDC_PLAYLIST_SOURCE_CLEARFILTER 1037
#define IDC_PLAYLIST_FILTER             1038
#define IDC_PLAYLIST_LIST               1039
#define IDC_CDSOURCE_TRACKLIST          1040
#define IDC_CDSOURCE_IMPORT             1041
#define IDC_AUDIOPLUGIN_CONFIGURE       1042
#define IDC_AUDIOPLUGIN_ABOUT           1043
#define IDC_AUDIOPLUGINS_LIST           1044
#define IDC_GENRECHK                    1045
#define IDC_RATINGCHK                   1046
#define IDC_ALBUMNAMECHK                1047
#define IDC_TRACKNUMCHK                 1048
#define IDC_TRACKYEARCHK                1049
#define IDC_TRKTITLECHK                 1050
#define IDC_ARTISTCHK                   1051
#define IDC_BUFFERING_INFO              1052
#define IDC_VISUAL_FPS                  1053
#define IDC_SOURCE_ADDPLAYLIST          1054
#define IDC_SOURCE_DELPLAYLIST          1055
#define IDC_CDTITLE                     1056
#define IDC_PREFERENCES_TREE            1057
#define IDC_INTERFACE_TASKBAR_NORMAL    1058
#define IDC_INTERFACE_TASKBAR_MINIMIZE  1059
#define IDC_INTERFACE_HISTORYCOUNT_SPINNER 1060
#define IDC_INTERFACE_FOLLOWCURRENTSONG 1061
#define IDC_INTERFACE_HISTORYCOUNT      1062
#define IDC_INTERFACE_FUTURECOUNT_SPINNER 1063
#define IDC_INTERFACE_FUTURECOUNT       1064
#define IDC_INTERFACE_SMARTSORTING      1065
#define IDC_INTERFACE_ARTONSELECTION    1066
#define IDC_INTERFACE_SHOWVISART        1067
#define IDC_INTERFACE_SHOWALBUMART      1068
#define IDC_FORMATTING_WINDOWTITLEFORMAT 1069
#define IDC_FORMATTING_PLUGINFORMAT     1070
#define IDC_FORMATTING_LISTFORMAT       1071
#define IDC_FORMATTING_PLAYLINE1FORMAT  1072
#define IDC_FORMATTING_PLAYLINE2FORMAT  1073
#define IDC_FORMATTING_FORMATSTRING_HELP 1074
#define IDC_GENERAL_PAUSEONSCREENSAVE   1075
#define IDC_GENERAL_CLOSEONSCREENSAVE   1076
#define IDC_GENERAL_PAUSEONLOCK         1077
#define IDC_GENERAL_CLOSEONLOCK         1078
#define IDC_GENERAL_CLOSEONSWITCH       1079
#define IDC_GENERAL_NOVKHOTKEYS         1080
#define IDC_GENERAL_SKIPSTREAMS         1081
#define IDC_PLAYLIST_SOURCE_SELECTFILTERBYFIELD 1082
#define IDC_PLAYLISTSOURCE_FILTERCOMBO  1083
#define IDC_BUFFERING_CANCEL            1084
#define IDC_PLUGINS_LIST                1085
#define IDC_PLUGINS_ABOUT               1086
#define IDC_PLUGINS_CONFIGURE           1087
#define IDC_PLUGINS_DISABLEALL          1088
#define IDC_PLUGINS_ENABLEALL           1089
#define IDC_OK                          1090
#define IDC_INTERFACE_MINIMIZEONCLOSE   1091
#define IDC_DEVICESELECTOR_COMBO        1092
#define IDC_VISUAL_CHANGERESCOMBO       1093
#define IDC_VISUAL_FPSDISPLAY           1094
#define IDC_VISUAL_CHANGERESCHECK       1095
#define IDC_LOGVIEW_EDIT                1096
#define IDC_LOGVIEW_CLEAR               1097
#define IDC_LOGVIEW_ENABLE              1098
#define IDC_AUDIO_AMPGAINSLIDER         1099
#define IDC_AUDIO_AMPGAINTEXT           1100
#define IDC_AUDIO_REPLAYGAIN            1101
#define IDC_AUDIO_REPLAYGAINALBUM       1102
#define IDC_LIBRARY_SKIPPLAYLISTIMPORT  1103
#define IDC_LIBRARY_PLAYLISTSORTING     1104
#define IDC_LIBRARY_AUTOADDPLAYLIST     1105
#define IDC_LIBRARY_ADDSINGLESTREAM     1106
#define IDC_FILEASSOC_TYPEDEFAULT_UPDATE 1107
#define IDC_FILEASSOC_TYPEDEFAULT       1108
#define IDC_FILEASSOC_TYPE_OPEN         1109
#define IDC_FILEASSOC_TYPE_PLAY         1110
#define IDC_FILEASSOC_TYPE_QUEUE        1111
#define IDC_FILEASSOC_SETDEFAULT        1112
#define IDC_FILEASSOC_ADDTHESE          1113
#define IDC_FILEASSOC_ACTIONTEXT        1114
#define IDC_FILEASSOC_WARNINGTEXT       1115
#define IDC_FILEASSOC_REGASSOC          1116
#define IDC_EQLOW_SLIDER                1117
#define IDC_EQMID_SLIDER                1118
#define IDC_EQHIGH_SLIDER               1119
#define IDC_EQLOW_TEXT                  1120
#define IDC_EQMID_TEXT                  1121
#define IDC_EQHIGH_TEXT                 1122
#define IDC_EQ_GROUP                    1123
#define IDC_EQRESET_BUTTON              1124
#define IDC_EQ_ENABLE                   1125
#define IDC_GENERAL_SCREEN_ALLOW        1126
#define IDC_GENERAL_SCREEN_PREVENT      1127
#define IDC_GENERAL_SCREEN_PREVENTFULL  1128
#define IDC_GENERAL_PAUSEONSWITCH       1129
#define IDC_GENERAL_REMEMBERPOS         1130
#define IDC_GENERAL_ONLOCKTEXT          1131
#define IDC_GENERAL_REMEMBERPOSTEXT     1132
#define IDC_GENERAL_ONSCREENSAVETEXT    1133
#define IDC_GENERAL_RESUMEONSCREENSAVE  1134
#define IDC_GENERAL_RESUMEONLOCK        1135
#define IDC_GENERAL_RESUMEONSWITCH      1136
#define IDC_GENERAL_ONSWITCHTEXT        1137
#define IDC_GENERAL_DELAYINSECS         1138
#define IDC_GENERAL_DELAYINSECSTEXT     1139
#define IDC_GENERAL_AUTOSOFTPAUSE       1140
#define IDC_USERSEARCHFIELD_SELECTEDLIST 1141
#define IDC_USERSEARCHFIELD_ADD         1142
#define IDC_USERSEARCHFIELD_REMOVE      1143
#define IDC_USERSEARCHFIELD_CLEAR       1144
#define IDC_USERSEARCHFIELD_DEFAULT     1145
#define IDC_USERSEARCHFIELD_AVAILABLELIST 1146
#define IDC_TUNIACVISPREF_FILLSTRIP     1147
#define IDC_TUNIACVISPREF_SHIFTRATE_SLIDER 1148
#define IDC_TUNIACVISPREF_SHIFTRATE_TEXT 1149
#define IDC_TUNIACVISPREF_CLEARRATE_SLIDER 1150
#define IDC_TUNIACVISPREF_CLEARRATE_TEXT 1151
#define IDC_SERVICEPLUGIN_CONFIGURE     1211
#define IDC_SERVICEPLUGIN_ABOUT         1212
#define IDC_SERVICEPLUGIN_DISABLEALL    1213
#define IDC_SERVICEPLUGIN_ENABLEALL     1214
#define IDC_SERVICEPLUGIN_LIST          1215
#define IDC_ABOUT_TUNIACORG             2000
#define ID_FILE_EXIT                    40001
#define ID_FILE_NEWPLAYLIST_NORMALPLAYLIST 40002
#define ID_FILE_NEWPLAYLIST_SMARTPLAYLIST 40003
#define ID_FILE_ADDFILES                40004
#define ID_FILE_ADDDIRECTORY            40005
#define ID_FILE_ADDOTHER                40006
#define ID_FILE_OPENSTREAM              40007
#define ID_FILE_FORCESAVEMEDIALIBRARY   40008
#define ID_EDIT_PREFERENCES             40009
#define ID_EDIT_EDITFILEINFORMATION     40010
#define ID_EDIT_SHOWCOLUMNSELECTION     40011
#define ID_HELP_ABOUT                   40012
#define ID_HELP_TUNIACHELP              40013
#define ID_HELP_HOMEPAGE                40014
#define ID_REPEAT_OFF                   40015
#define ID_REPEAT_ONETRACK              40016
#define ID_REPEAT_ALLTRACKS             40017
#define ID_REPEAT_ALLQUEUED             40018
#define ID_VIS_CONFIGURE                40019
#define ID_VIS_ABOUT                    40020
#define ID_VIS_FULLSCREEN               40021
#define ID_APP_SHOW                     40022
#define ID_PLAY                         40023
#define ID_REMOVE                       40024
#define ID_UPDATE                       40025
#define ID_TONEWPLAYLIST                40026
#define ID_FILTERBYFIELD                40027
#define ID_PLAYPLAYLIST                 40028
#define ID_PAUSEHERE                    40029
#define ID_PLAYBACK_NEXT                40030
#define ID_PLAYBACK_PREVIOUS            40031
#define ID_PLAYBACK_PLAYPAUSE           40032
#define ID_PLAYBACK_CLEARQUEUE          40033
#define ID_PLAYBACK_PREVIOUS_BYHISTORY  40034
#define ID_PLAYBACK_SOFTPAUSE           40035
#define ID_PLAYBACK_SEEKFORWARD         40036
#define ID_PLAYBACK_SEEKBACK            40037
#define ID_PLAYBACK_STOP                40038
#define ID_PLAYBACK_PAUSE               40039
#define ID_PLAYBACK_PLAY                40040
#define ID_PLAYBACK_TOGGLE_SHUFFLE      40041
#define ID_PLAYBACK_TOGGLE_REPEAT       40042
#define ID_PLAYBACK_VOLUMEUP            40043
#define ID_PLAYBACK_VOLUMEDOWN          40044
#define ID_PLAYBACK_VOLUMEMUTE          40045
#define ID_PLAYBACK_RANDOMNEXT          40046
#define ID_PLAYBACK_CLEARPAUSEAT        40047
#define ID_PLAYBACK_REPEATMODE          40048
#define ID_PLAYBACK_SHOWCURRENTLYPLAYINGTRACK 40049
#define ID_FILTERBY_ARTIST              40101
#define ID_FILTERBY_NORMAL              40102
#define ID_FILTERBY_TITLE               40103
#define ID_FILTERBY_ALBUM               40104
#define ID_FILTERBY_GENRE               40105
#define ID_FILTERBY_YEAR                40106
#define ID_FILTERBY_COMMENT             40107
#define ID_FILTERBY_URL                 40108
#define ID_FILTERBY_FILENAME            40109
#define ID_FILTERBY_EXTENSION           40110
#define ID_FILTERBY_ALBUMARTIST         40111
#define ID_FILTERBY_COMPOSER            40112
#define ID_PLAYLISTS                    40113
#define ID_PLAYLISTS_MEDIALIBRARY       40114
#define ID_FIND                         40115
#define ID_RENAME                       40116
#define ID_COPYTO                       40117
#define ID_MERGEINTO                    40118
#define ID_REMOVEFROM                   40119
#define ID_QUEUEBYFIELD                 40120
#define ID_FILE_EXPORTPLAYLIST          40121
#define ID_EXPORT                       40122
#define ID_REMOVEDUPLICATES             40123
#define ID_FILTERBY                     40124
#define ID_SHOWFILE                     40125
#define ID_EDIT_ALWAYSONTOP             40126
#define ID_SAVEORDER                    40127
#define ID_RESTOREORDER                 40128
#define ID_PLAYNEXT                     40129
#define ID_QUEUE                        40130

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         40149
#define _APS_NEXT_CONTROL_VALUE         1216
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
