//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tuniac.rc
//
#define IDR_TUNIAC_MENU                 101
#define IDD_ALBUMARTISTVIEW             101
#define IDD_SOURCESELECTOR              102
#define IDD_ADDOTHER                    103
#define IDD_ADDINGFILES                 104
#define IDD_PLAYLISTSOURCE              107
#define IDD_PREFERENCES_AUDIO           108
#define IDI_TUNIAC                      109
#define IDI_MEDIALIBRARY                110
#define IDI_THEMEICON_PLAYLIST_MEDIALIBRARY 110
#define IDC_ADDARROW                    113
#define IDD_ALBUMFILTER                 114
#define IDC_NEWPLAYLISTARROW            114
#define IDI_PLAYLIST                    115
#define IDI_THEMEICON_PLAYLIST_STANDARD 115
//#define IDI_RADIOTUNER                  116
#define IDD_EDITOR_SONG                 120
#define IDD_EDITOR_FILE                 121
#define IDD_EDITOR_MISC                 122
#define IDD_PLAYLISTVIEW_VIEWOPTIONS    123
#define IDD_PREFERENCES_MEDIALIBRARY    124
#define IDR_MAINWINDOWACCEL             124
#define IDD_PREFERENCES_COREAUDIO       125
#define IDI_CDDRIVE                     126
#define IDD_CDAUDIOSOURCE               126
#define IDI_THEMEICON_PLAYLIST_CD       126
#define IDD_PREFERENCES_IMPORTING       127
#define IDD_BUFFERING                   129
#define IDR_VISMENU                     130
#define IDD_PREFERENCES_VISUALS         131
#define IDD_SAVINGLIBRARY               132
#define IDD_PREFERENCES_GENERAL         133
#define IDD_PREFERENCES_FILEASSOC       134
#define IDR_TRAYMENU                    135
#define IDD_PREFERENCES_PLUGINS         135
#define IDR_PLAYLISTITEM_MENU           136
#define IDR_SOURCESELECT_MENU           138
#define IDR_FILTERBYFIELD_MENU          143
#define IDR_SOURCESELECT_DRAGMENU       144
#define IDI_THEMEICON_ITEM_NORMAL       159
#define IDI_THEMEICON_ITEM_ACTIVE       161
//#define IDI_THEMEICON_PLAYLIST_RADIO    162
#define IDD_PREFERENCES                 163
#define IDD_PREFERENCES_FORMATTING      164
#define IDR_PLAYLISTHEADER_MENU         165
#define IDD_LOGVIEW                     166
//#define IDD_RADIOSOURCEVIEW             167
#define IDB_BITMAP1                     178
#define IDB_EDITINFO                    178
#define IDB_NEXT                        179
#define IDB_PAUSE                       180
#define IDB_PLAY                        181
#define IDB_PREVIOUS                    182
#define IDB_REPEATALL                   183
#define IDB_REPEATNONE                  184
#define IDB_REPEATONE                   185
#define IDB_SHUFFLEOFF                  186
#define IDB_SHUFFLEON                   187
#define IDR_RT_MANIFEST1                192
#define IDC_ADDOTHER_ADD                1001
#define IDC_ADDOTHER_EDIT               1002
#define IDC_ADDOTHER_CANCEL             1003
#define IDC_ADDINGFILES_PROGRESS        1004
#define IDC_BUFFERING_PROGRESS          1004
#define IDC_SOURCESELECTOR              1005
#define IDC_LIBRARY_LIST                1006
//#define IDC_RADIO_STATIONLIST           1007
//#define IDC_RADIO_TOPPICKS              1008
#define IDC_LIBRARY_FILTER              1009
#define IDC_PLAYLIST_FILTER             1009
#define IDC_PLAYLIST_LIST               1010
#define IDC_CROSSFADE_ENABLE            1012
#define IDC_CROSSFADE_TIME_SLIDER       1013
#define IDC_PLAYLIST_ALBUMSELECTOR      1038
#define IDD_FILTERSELECTOR              1040
#define IDC_FILTER_ARTIST               1041
#define IDC_CROSSFADE_TIME_TEXT         1042
#define IDC_EDIT1                       1043
#define IDC_TITLE_EDIT                  1043
#define IDC_ARTIST_COMBO                1044
#define IDC_RATING_CONTROL              1045
#define IDC_TRACKNO_EDIT                1045
#define IDC_PLAYTIME_TEXT               1046
#define IDC_TRACKMAX_EDIT               1046
#define IDC_SAMPLERATE_TEXT             1047
#define IDC_ALBUM_COMBO                 1047
#define IDC_CHANNELS_TEXT               1048
#define IDC_YEAR_EDIT                   1048
#define IDC_BITRATE_TEXT                1049
#define IDC_GENRE_COMBO                 1050
#define IDC_PLAYLISTVIEWOPTIONS_LIST    1051
#define IDC_BUTTON1                     1052
#define IDC_BUTTON2                     1053
#define IDC_BUTTON3                     1054
#define IDC_PLAYLIST_SOURCE_MAKEPLAYLIST 1055
#define IDC_PLAYLIST_SOURCE_CLEARFILTER 1056
//#define IDC_RADIOSOURCE_TOPPICKSLIST    1057
//#define IDC_RADIOSOURCE_STATIONLIST     1058
#define IDC_ALBUMARTIST_ALBUMLIST       1059
#define IDC_ALBUMARTIST_ARTISTLIST      1060
#define IDC_ALBUMARTIST_PLAYLISTLIST    1062
//#define IDC_RADIOSOURCE_REFRESH         1063
#define IDC_LIST1                       1064
#define IDC_CDSOURCE_TRACKLIST          1064
//#define IDC_RADIOSOURCE_LIST            1064
#define IDC_AUDIOPLUGIN_CONFIGURE       1065
#define IDC_AUDIOPLUGIN_ABOUT           1066
#define IDC_GENRECHK                    1067
#define IDC_RATINGCHK                   1068
#define IDC_ALBUMNAMECHK                1069
#define IDC_TRACKNUMCHK                 1070
#define IDC_TRACKYEARCHK                1071
#define IDC_TRKTITLECHK                 1072
#define IDC_ARTISTCHK                   1073
#define IDC_BUFFERING_INFO              1074
#define IDC_VISUALPREFS_FPS             1075
#define IDC_AUDIOPLUGINS_LIST           1076
#define IDC_PROGRESS1                   1078
#define IDC_SAVINGLIBRARY_PROGRESS      1078
#define IDC_SOURCE_ADDPLAYLIST          1081
#define IDC_SOURCE_DELPLAYLIST          1082
#define IDC_DTITLE                      1084
#define IDC_CDTITLE                     1085
#define IDC_GENERAL_TASKBAR_NORMAL      1089
#define IDC_GENERAL_TASKBAR_MINIMIZE    1090
#define IDC_RADIO4                      1092
#define IDC_GENERAL_PAUSEONLOCK         1093
#define IDC_GENERAL_FOLLOWCURRENTSONG   1094
#define IDC_GENERAL_WINDOWTITLEFORMAT   1095
#define IDC_GENERAL_WINDOWFORMATSTRING  1095
#define IDC_FORMATTING_WINDOWTITLEFORMAT 1095
#define IDC_GENERAL_PLUGINFORMATSTRING  1096
#define IDC_FORMATTING_PLUGINFORMAT     1096
#define IDC_GENERAL_LISTFORMATSTRING2   1097
#define IDC_GENERAL_LISTFORMATSTRING    1097
#define IDC_FORMATTING_LISTFORMAT       1097
#define IDC_GENERAL_WINDOWTITLEFORMAT_HELP 1098
#define IDC_GENERAL_FORMATSTRING_HELP   1098
#define IDC_FORMATTING_FORMATSTRING_HELP 1098
#define IDC_FILEASSOC_LIST              1102
#define IDC_FILEASSOC_SELECTALL         1103
#define IDC_FILEASSOC_DESELECTALL       1104
#define IDC_FILEASSOC_ASSOCNOW          1105
#define IDC_FILEASSOC_reseT             1106
#define IDC_FILEASSOC_RESET             1106
#define IDC_FILEASSOC_TYPE_OPEN         1108
#define IDC_FILEASSOC_TYPE_PLAY         1109
#define IDC_FILEASSOC_TYPE_QUEUE        1110
#define IDC_ADDINGFILES_COUNT           1111
#define IDC_GENERAL_PAUSEONSCREENSAVE   1112
#define IDC_GENERAL_HISTORYCOUNT_SPINNER 1114
#define IDC_GENERAL_HISTORYCOUNT        1115
#define IDC_GENERAL_FUTURECOUNT_SPINNER 1116
#define IDC_GENERAL_FUTURECOUNT         1117
#define IDC_PLAYLIST_SOURCE_SELECTFILTERBYFIELD 1118
#define IDC_GENERAL_SMARTSORTING        1119
#define IDC_FILEASSOC_TYPEDEFAULT       1120
#define IDC_FILEASSOC_TYPEDEFAULT_UPDATE 1121
#define IDC_BUFFERING_CANCEL            1121
#define IDC_THEMESELECTOR               1122
#define IDC_GENERAL_THEMESELECTOR       1122
#define IDC_PLUGINS_LIST                1123
#define IDC_PLUGINS_ABOUT               1124
#define IDC_PLUGINS_CONFIGURE           1125
#define IDC_PLUGINS_DISABLEALL          1126
#define IDC_PLUGINS_ENABLEALL           1127
#define IDC_PREFERENCES_TREE            1128
#define IDC_OK                          1129
#define IDC_PLAYLISTSOURCE_FILTERCOMBO  1136
#define IDC_GENERAL_MINIMIZEONCLOSE     1137
#define IDC_COMBO1                      1138
#define IDC_DEVICESELECTOR_COMBO        1138
#define IDC_RADIO1                      1139
#define IDC_RADIO2                      1140
#define IDC_VISUALPREFS_FPSDISPLAY      1141
#define IDC_CHECK1                      1142
#define IDC_CDSOURCE_IMPORT             1143
#define IDC_LOGVIEW_EDIT                1144
#define IDC_LOGVIEW_CLEAR               1145
#define IDC_LOGVIEW_ENABLE              1146
//#define IDC_RADIOSOURCE_TUNEIN          1147
#define ID_FILE_EXIT                    40001
#define ID_FILE_NEWPLAYLIST_NORMALPLAYLIST 40002
#define ID_FILE_NEWPLAYLIST_SMARTPLAYLIST 40003
#define ID_FILE_ADDFILES                40004
#define ID_FILE_ADDDIRECTORY            40005
#define ID_FILE_ADDOTHER                40006
#define ID_EDIT_PREFERENCES             40007
#define ID_HELP_ABOUT                   40009
#define ID_EDIT_EDITFILEINFORMATION     40012
#define ID_HELP_TUNIACHELP              40013
#define ID_HELP_CHECKFORUPDATES         40014
#define ID_PLAYBACK_NEXT                40015
#define ID_PLAYBACK_PREVIOUS            40016
#define ID_PLAYBACK_PLAYPAUSE           40017
#define ID_FILE_OPENSTREAM              40018
#define ID_PLAYBACK_REPEATMODE          40019
#define ID_EDIT_SHOWVIEWOPTIONS         40021
#define ID_REPEAT_OFF                   40028
#define ID_REPEAT_ONETRACK              40030
#define ID_REPEAT_ALLTRACKS             40031
#define ID__PLUGIN                      40032
#define ID_VIS_CONFIGURE                40038
#define ID_VIS_ABOUT                    40039
#define ID_FILE_FORCESAVEMEDIALIBRARY   40040
#define ID_EDIT_SHOWCURRENTLYPLAYINGTRACK 40041
#define ID_VIS_FULLSCREEN               40045
#define ID_APP_SHOW                     40048
#define ID_PLAYBACK_SEEKFORWARD         40050
#define ID_PLAYBACK_SEEKBACK            40051
#define ID_PLAYBACK_STOP                40052
#define ID_PLAYBACK_PAUSE               40053
#define ID_PLAYBACK_PLAY                40054
#define ID_PLAYBACK_TOGGLE_SHUFFLE      40055
#define ID_PLAYBACK_TOGGLE_REPEAT       40056
#define ID_PLAY                         40059
#define ID_REMOVE                       40062
#define ID_TONEWPLAYLIST                40066
#define ID_FILTERBYFEILD                40067
#define ID_PLAYPLAYLIST                 40069
#define ID_PAUSEHERE                    40071
#define ID_PLAYBACK_SOFTPAUSE           40072
#define ID_EDIT_ALWAYSONTOP             40073
#define ID_PLAYNEXT                     40080
#define ID_QUEUE                        40081
#define ID_PLAYBACK_CLEARQUEUE          40082
#define ID_PLAYBACK_PREVIOUS_BYHISTORY  40090
#define ID_REPEAT_ALLQUEUED             40093
#define ID_FILTERBY_ARTIST              40105
#define ID_FILTERBY_NORMAL              40106
#define ID_FILTERBY_TITLE               40107
#define ID_FILTERBY_ALBUM               40108
#define ID_FILTERBY_GENRE               40109
#define ID_FILTERBY_YEAR                40110
#define ID_FILTERBY_COMMENT             40111
#define ID_FILTERBY_URL                 40112
#define ID_FILTERBY_FILENAME            40113
#define ID_FILTERBY_EXTENSION           40114
#define ID_PLAYBACK_RANDOMNEXT          40115
#define ID_Menu                         40116
#define ID__PLAYLISTS                   40118
#define ID_PLAYLISTS_MEDIALIBRARY       40119
#define ID_PLAYBACK_CLEARPAUSEAT        40121
#define ID_RENAME                       40122
#define ID_COPYTO                       40126
#define ID_MERGEINTO                    40127
#define ID_REMOVEFROM                   40128
#define ID_QUEUEBYFIELD                 40130
#define ID_FILE_EXPORTPLAYLIST          40131
#define ID_EXPORT                       40134
#define ID_REMOVEDUPLICATES             40135
#define ID_FILTERBY                     40141
#define ID_FILTERBY_YEP                 40142
#define ID_SHOWFILE                     40148

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         40149
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
